/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :May 08, 2014,TIME->12:04:19                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :Sim900.c*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#include "Sim900.h"
#include "BSP.h"

volatile static struct GsmEvent Gsm;
volatile GsmEventPointer GsmPtr =&Gsm;




#define GSMCommNo 6 //uart channel



romchar AT[] =  {"AT\r\n"};   
romchar ATE0[] =  {"ATE0\r\n"};   
romchar CREG[] =  {"AT+CREG?\r\n"};   
romchar CENG[] =  {"AT+CENG?\r\n"};   
romchar CSQ[] =  {"AT+CSQ\r\n"};   
romchar CGCLASS[]= {"AT+CGCLASS=\"B\"\r\n"};   
romchar CGDCONT[]={"AT+CGDCONT=1,\"IP\","};//\"airtelgprs.com\"\r\n"};  
 
romchar CGATT[]={"AT+CGATT=1\r\n"};   
romchar CGATT0[]={"AT+CGATT=0\r\n"};   

romchar CIICR[]={"AT+CIICR\r\n"};//\"airtelgprs.com\",\"\",\"\"\r\n"  
romchar CIFSR[]={"AT+CIFSR\r\n"};

romchar CIPCSGP[]={"AT+CIPCSGP=1,"};//\"airtelgprs.com\"\r\n"};   
romchar CSTT[]={"AT+CSTT="};//\"airtelgprs.com\"\r\n"}; 

romchar CIPSTART[] ={"AT+CIPSTART=\"TCP\","};//\"64.27.25.155\",\"10020\"\r\n"};

romchar CIPSHUT [] ={"AT+CIPSHUT\r\n"};
romchar CIPCLOSE [] ={"AT+CIPCLOSE\r\n"};

romchar CLPORT [] ={"AT+CLPORT=\"TCP\","};//\"0001\"\r\n"};

romchar CIPSEND[] ={"AT+CIPSEND\r\n"};
romchar CMGS[] =   {"AT+CMGS=\"9033263902\"\r\n"};

romchar EOD[] = {0x1a,0x00};
romchar CIPSTATUS [] ={"AT+CIPSTATUS\r\n"};



void Tcp()
{
			#ifdef DebugOn
			GsmDisplayUpdate("Tcp Connected",1);
			#endif
			switch(Gsm.Tcp_State)
			{
				case T_Sending:
				ToSend(RegularUpdate);
				Gsm_Control(Tcp_Connection,T_Send,T_Send,T_Sending,2,20,TimerStart);
				break;//T_Sending
				case T_Send:
				nop();
				break;//T_Send
			}
			

	
}


void Tcp_Init()
{
	switch (Gsm.Tcp_State)
	{
				
		case T_CCGDCONT:
		break;//T_CCGDCONT
		
		case T_CCGATT:
		break;//T_CCGATT
		
		case T_Init:
				#ifdef DebugOn
				   GsmDisplayUpdate("AT ",1)	;	
				#endif		
				 GsmClearBufffer();
				 drv_sim900_send_cmd(get_size(AT),AT); 
				 Gsm_Control(Tcp_Connection,T_Started,T_CATE0,T_Init,Gsm.Delay,Gsm.MaxDelay,TimerStart);
				 

		break;//T_Init
		case T_CATE0:
				#ifdef DebugOn
				   GsmDisplayUpdate("AT OK",1)	;	
				#endif		
 				 drv_sim900_send_cmd(get_size(ATE0),ATE0);
				 Gsm_Control(Tcp_Connection,T_Started,T_CCREG,T_CATE0,Gsm.Delay,Gsm.MaxDelay,TimerStart);

		break; //T_CAT
		
		case T_CCREG:
				#ifdef DebugOn
				   GsmDisplayUpdate("CATE0 OK",1)	;	
				#endif		
		GsmClearBufffer();
		drv_sim900_send_cmd(get_size(CREG),CREG); 
		Gsm_Control(Tcp_Connection,T_Started,T_CCIPSTATUS,T_CCREG,Gsm.Delay,Gsm.MaxDelay,TimerStart);

		break;//T_CCREG
		
		case T_CCIPSTATUS://CREG OK
		#ifdef DebugOn
			   GsmDisplayUpdate("CCREG OK    ",1)	;	
		#endif		
		GsmClearBufffer();
		drv_sim900_send_cmd(14,CIPSTATUS); //ok state Ip intial
		Gsm_Control(Tcp_Connection,T_Started,T_CCIPSTATUS,T_CCIPSTATUS,Gsm.Delay,Gsm.MaxDelay,TimerStart);

		break;//T_CCIPSTATUS

		case T_CCSTT:
		#ifdef DebugOn
			   GsmDisplayUpdate("CSTT     ",1)	;	
		#endif			
		  GsmClearBufffer();
		  Gsm_Control(Tcp_Connection,T_Started,T_CCIPSTATUS,T_CCSTT,Gsm.Delay,Gsm.MaxDelay,TimerStart);
          drv_sim900_send_cmd(get_size(CSTT),CSTT);  
          drv_sim900_send_cmd(1,"\"");                     
		  drv_sim900_send_cmd(get_size("INTERNET"),"INTERNET");                 
          drv_sim900_send_cmd(1,"\"");
          drv_sim900_send_cmd(6,",\"\",\"\""); // ,"",""
          drv_sim900_send_cmd(2,"\r\n");    
		break;//T_CCIPSTATUS,
		

		case T_CCIPCSGP:
		break;//T_CCIPCSGP
	
		case T_CCIICR:
		#ifdef DebugOn
			   GsmDisplayUpdate("CIICR     ",1)	;	
		#endif			
		  GsmClearBufffer();
		  Gsm_Control(Tcp_Connection,T_Started,T_CCIPSTATUS,T_CCIICR,Gsm.Delay,Gsm.MaxDelay,TimerStart);
          drv_sim900_send_cmd(get_size(CIICR),CIICR); 
		
		break;//T_CCSTT
		
		case T_CLPORT :
		#ifdef DebugOn
			   GsmDisplayUpdate("CLPORT    ",1)	;	
		#endif		
				GsmClearBufffer();
				Gsm_Control(Tcp_Connection,T_Started,T_CCIFSR,T_CLPORT,Gsm.Delay,Gsm.MaxDelay,TimerStart);
        		drv_sim900_send_cmd(get_size(CLPORT),CLPORT);         
             	drv_sim900_send_cmd(1,"\"");                     
              	drv_sim900_send_cmd(get_size("60"),"60");                 
              	drv_sim900_send_cmd(3,"\"\r\n");                     
		
    
	break;//T_CLPORT
		
		case T_CCIPSTART:
		#ifdef DebugOn
			   GsmDisplayUpdate("CCIPSTART    ",1)	;	
		#endif		
		GsmClearBufffer();
		Gsm_Control(Tcp_Connection,T_Started,T_CCIFSR,T_CCIPSTART,5,Gsm.MaxDelay,TimerStart);
        drv_sim900_send_cmd(get_size(CIPSTART),CIPSTART);   
        drv_sim900_send_cmd(1,"\"");                     
        drv_sim900_send_cmd(get_size(Gsm.Ip_ADD),Gsm.Ip_ADD);   //"64.27.25.155\",\"10020\"\r\n"              
        drv_sim900_send_cmd(3,"\",\""); 
        drv_sim900_send_cmd(get_size(Gsm.PortNo),Gsm.PortNo);                 
        drv_sim900_send_cmd(3,"\"\r\n");                         
		break;//T_CCIFSR
		
		case T_CCIFSR:
		#ifdef DebugOn
			   GsmDisplayUpdate(" CCIFSR ",1)	;	
		#endif		
		GsmClearBufffer();
       	drv_sim900_send_cmd(get_size(CIFSR),CIFSR); 
		Gsm_Control(Tcp_Connection,T_Started,T_CCIPSTART,T_CCIFSR,Gsm.Delay,Gsm.MaxDelay,TimerStart);

		break;//T_CCIPSTART,
		
		
		case T_CCIPSHUT:
				#ifdef DebugOn
			   GsmDisplayUpdate(" CIPSHUT ",1)	;	
		#endif		
				GsmClearBufffer();
				 drv_sim900_send_cmd(12,"AT+CIPSHUT\r\n");
				 Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);
		break;//T_CCIPSHUT
		
		case T_Started:
		if(Gsm.Tcp_OldState==T_CCIFSR )
		{
			Gsm.Tcp_State=T_CCIPSTART;
		}
		

		switch (Gsm.Tcp_Evt)
		{
			case IP_INITIAL:
			Gsm.Tcp_State=T_CCSTT;
			break;//IP_INITIAL
			case IP_GPRSACT:
			Gsm.Tcp_State=T_CCIFSR;
			break;//IP_GPRSACT
			
			case IP_START:
			GsmClearBufffer();
			Gsm.Tcp_State=T_CCIICR;
			break;
			
			case IP_CONFIG:
			break;
			case Tcp_CREG_oK:
			Gsm.Tcp_State=T_CCIPSTATUS;
			break;//IP_CONFIG
			case PDP_DEACT:
			break;//PDP_DEACT
			
			case TCP_CLOSED:
			break;//TCP_CLOSED
			case TCP_CONNECTING:
			Gsm.Tcp_State=T_CCIPSTATUS;
			break;//TCP_CONNECTING
			case CONNECT_OK:

			Gsm.Tcp_Stage=Tcp_Connected;

			break;//CONNECT_OK
			case TCP_OK:
			
				switch(Gsm.Tcp_OldState)
				{
				case T_Init:
						Gsm.Tcp_State=T_CATE0;
				break;
				case T_CATE0:
					Gsm.Tcp_State=T_CCREG;
					break;
				case T_CCSTT:
					Gsm.Tcp_State=T_CCIPSTATUS;
					break;
				case T_CCIICR:
				Gsm.Tcp_State=T_CLPORT;
					break;
				case T_CLPORT:	
				Gsm.Tcp_State=T_CCIPSTATUS;
					break;

				}
			break;//TCP_OK
			case Tcp_Error:
					GsmClearBufffer();
					Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);
			break;			
			
		}
		Gsm.Tcp_Evt=Tcp_Default;
		break;//T_Started
		
		case T_completed:
		Gsm_Control(Tcp_Connected,T_Init,T_Started,T_Init,1,10,TimerStart);
		break;//T_completed
	}
}

	


 




unsigned char GsmCheckMsg()
{
	static unsigned int i=0,j=0;
	
	i=0;
	while(++i<GsmRXBufferSize)
	{
						if(GsmPtr->Rxbuff[i] == 'O' && GsmPtr->Rxbuff[i+1] == 'K' &&  GsmPtr->Rxbuff[i+3] == '\n')        
	                    {                         
								
								switch(Gsm.ConnectionStatus)
									{
										 case InitGsm:
										 case OkGsm:
										 Gsm.MsgStatus=MsgOk;
										 return 1; 
										 break;//InitGsm
										 case TcpConnecting:

											switch(Gsm.Tcp_OldState)
											{
												case T_Init:
												case T_CATE0:
												case T_CCSTT:
												case T_CLPORT:
												case T_CCIICR:
												case T_CCIFSR:
												Gsm.Tcp_Evt=TCP_OK;
												return 1; 
												break;
												default:
												break;
												
											}

										 break;//TcpConnecting

									}	
								                      
						}
						 if(GsmPtr->Rxbuff[i] == ';'|| GsmPtr->Rxbuff[i] == 0x02)       // check start of message frame/fare frame
				        {
 							nop();
				        } 
						 
						 
					   if(GsmPtr->Rxbuff[i]=='S'&& GsmPtr->Rxbuff[i+1]=='M')
						{
							Gsm.Event=EvtGsmMsg;
							return 1;
						}
						else if((GsmPtr->Rxbuff[i]=='R')&&(	GsmPtr->Rxbuff[i+1]=='I'))
						{
							Gsm.Event=EvtGsmRing;
							return 1;
						} 			
						else if((GsmPtr->Rxbuff[i]=='C')&&(	GsmPtr->Rxbuff[i+1]=='S'))
						{
							if(GsmPtr->Rxbuff[i+6]==',')
							{	
								Gsm._Csq[0]=' '			;						
								Gsm._Csq[1]=' '			;		
								Gsm._Csq[2]=GsmPtr->Rxbuff[i+5]			;
								Gsm._Csq[3]=0			;
								Gsm.Rssi=atoi(&Gsm._Csq[0]);
								Gsm.Tcp_State=T_CsqReceived;
								return 1;
							}
						
							else if(GsmPtr->Rxbuff[i+7]==',')
							{
								Gsm._Csq[0]=' '; //space
								Gsm._Csq[1]=GsmPtr->Rxbuff[i+5]			;
								Gsm._Csq[2]=GsmPtr->Rxbuff[i+6]			;
								Gsm._Csq[3]=0			;
								Gsm.Rssi=atoi(&Gsm._Csq[0]);
								Gsm.Tcp_State=T_CsqReceived;								
								return 1;
							}
						}	
						else if(GsmPtr->Rxbuff[i] == 'E' && GsmPtr->Rxbuff[i+1] == 'R' && GsmPtr->Rxbuff[i+2] == 'R'&&  GsmPtr->Rxbuff[i+3] == 'O')
							{
									Gsm.Tcp_Evt=Tcp_Error;
								return 1;
							}
					    else if(GsmPtr->Rxbuff[i] == ':' &&  ((GsmPtr->Rxbuff[i+4] == '1')||(GsmPtr->Rxbuff[i+4] == '5')) && GsmPtr->Rxbuff[i+6] == '\n')   
		                    {
								Gsm.Tcp_Evt			=	Tcp_CREG_oK;
								return 1;
		                    }
		                else if(GsmPtr->Rxbuff[i] == ':' &&  ((GsmPtr->Rxbuff[i+1] == '1')||(GsmPtr->Rxbuff[i+1] == '2')) && GsmPtr->Rxbuff[i+6] == '\n')   
		                    {
								Gsm.Tcp_Evt			=	Tcp_CREG_oK;
								return 1;               
		                    }
	 					else if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+1] == 'O' && GsmPtr->Rxbuff[i+3] == 'I' && GsmPtr->Rxbuff[i+11] == '\n' )   
		                    {
		  						Gsm.Tcp_Evt=IP_CONFIG;
								
								return 1;  
		                    }
                    
	                    else if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+1] == 'L' && GsmPtr->Rxbuff[i+2] == 'O' && GsmPtr->Rxbuff[i+3] == 'S' && GsmPtr->Rxbuff[i+4] == 'E'  ) 
		                    {
								Gsm.Tcp_Evt=TCP_CLOSED;
								return 1;  
		                    }
					    else if(GsmPtr->Rxbuff[i] == 'I' && GsmPtr->Rxbuff[i+6] == 'T' && GsmPtr->Rxbuff[i+10] == 0X0D ) //ip initial
							{
							Gsm.Tcp_Evt=IP_INITIAL;	
							return 1; 
							}
		                else if(GsmPtr->Rxbuff[i] == 'I' && GsmPtr->Rxbuff[i+3] == 'S' && GsmPtr->Rxbuff[i+4] == 'T'&& GsmPtr->Rxbuff[i+7] == 'U'&& GsmPtr->Rxbuff[i+8] == 'S' &&  GsmPtr->Rxbuff[i+10] == 10 ) 
		                    {
		                       Gsm.Tcp_Evt=IP_STATUS;
							return 1; 	
		                    }	
 						else if(GsmPtr->Rxbuff[i] == 'G' && GsmPtr->Rxbuff[i+1] == 'P' && GsmPtr->Rxbuff[i+2] == 'R' && GsmPtr->Rxbuff[i+3] == 'S' && GsmPtr->Rxbuff[i+4] == 'A' && GsmPtr->Rxbuff[i+5] == 'C' )
		                    {
								Gsm.Tcp_Evt= IP_GPRSACT;
							
							   return 1;  
		                    }
	                    else if(GsmPtr->Rxbuff[i] == 'S' && GsmPtr->Rxbuff[i+1] == 'T' && GsmPtr->Rxbuff[i+2] == 'A' && GsmPtr->Rxbuff[i+3] == 'R' && GsmPtr->Rxbuff[i+4] == 'T')
		                    {
		                       Gsm.Tcp_Evt = IP_START;
							   return 1;
		                    }
                    	else if(GsmPtr->Rxbuff[i] == 'S' && GsmPtr->Rxbuff[i+1] == 'H' && GsmPtr->Rxbuff[i+2] == 'U' && GsmPtr->Rxbuff[i+3] == 'T' && GsmPtr->Rxbuff[i+8] == 0x0a)
		                    {
							switch(Gsm.ConnectionStatus)
									{
										 case OkGsm:
										 Gsm.MsgStatus=MsgOk;
										 return 1; 
										 break;//InitGsm
										 case TcpConnecting:
										// Gsm.Tcp_Evt =TCP_SHUT_OK;
										 break;//TcpConnecting
									}
								return 1;
		                    }
                    	else if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+9] == 'G' && GsmPtr->Rxbuff[i+11] == '\n' ) 
		                    {
		                       Gsm.Tcp_Evt = TCP_CONNECTING;                      
		                    }
					/*	else if(GsmPtr->Rxbuff[i] == 'E' && GsmPtr->Rxbuff[i+1] == 'R' && GsmPtr->Rxbuff[i+2] == 'R' && GsmPtr->Rxbuff[i+3] == 'O'&& GsmPtr->Rxbuff[i+4] == 'R' && GsmPtr->Rxbuff[i+6] == 0x0a )
							{
								  return 1;
							}*/
						else if(GsmPtr->Rxbuff[i] == 'F' && GsmPtr->Rxbuff[i+1] == 'A' && GsmPtr->Rxbuff[i+2] == 'I' && GsmPtr->Rxbuff[i+3] == 'L' && GsmPtr->Rxbuff[i+5] == 0x0a ) 
							{
								  return 1;
							}
                        else if(GsmPtr->Rxbuff[i] == 'P' && GsmPtr->Rxbuff[i+1] == 'D' && GsmPtr->Rxbuff[i+2] == 'P' && GsmPtr->Rxbuff[i+8] == 'T' && GsmPtr->Rxbuff[i+10] == 0x0a ) 
		                    {
								Gsm.Tcp_Evt = PDP_DEACT;
		                        return 1;
		                    }	
		               else if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+1] == 'O' && GsmPtr->Rxbuff[i+8] == 'O' && GsmPtr->Rxbuff[i+9] == 'K' )   
		                    {
		                        Gsm.Tcp_Evt = CONNECT_OK;
								return 1;     
		                    }
                    							
			}

			return 0;
}


void ToSend(enum GprsMsgType MsgType)
{
	switch(MsgType)
	{
		case RegularUpdate:
		//sprintf(Gsm.TxBuff,":SL%s_%ld,%s,%s,%d,%d,%d,%d,%d,%d,%d,%s,%s:%d,%u.%d,%d,%d,\r\n"
		sprintf(Gsm.TxBuff,":SL%s_%ld,%s,%s,%d,%d,%d,%d,%d,%d,%d,%s,%s,%u.%d,%d,%d,\r\n"
				  	,Navigation.D_Id,
					Navigation.BIDDING_ID,
					Navigation.Lat,
					Navigation.Lon,
				  	Navigation.FARE,
					Navigation.FARE_DEC,
					Navigation.DIST,
					Navigation.DIST_DEC,
				  	Navigation.WAITING_TIME_HOUR,
					Navigation.WAITING_TIME_MIN,
					Navigation.GMODE,
				  	Navigation.SPEED	,
					Navigation.TIMEBUFF,
					//PtrPCF8563->SEC,
					Navigation.ODDMETER,
				  	Navigation.ODDMETER_DEC,
					Navigation.FUEL,
					Navigation.IGNITION);
		break;//RegularUpdate
		
		case ButtonEvt:
		 /*sprintf(Gsm.TxBuff,":RP,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,\r\n",last_state->FARE,last_state->FARE_DEC,last_state->DIST,last_state->DIST_DEC,(last_state->WAITING_TIME/3600)%12,(last_state->WAITING_TIME/60)%60,
				  mstats->TOTAL_TRIP,mstats->TOTAL_FARE,mstats->TOTAL_FARE_DEC,mstats->TOTAL_PAID_KM,mstats->TOTAL_PAID_KM_DEC,mstats->TOTAL_FREE_KM,mstats->TOTAL_FREE_KM_DEC,mstats->TOTAL_WAITING_HR,mstats->TOTAL_WAITING_MIN,mstats->TOTAL_POWER_FAIL,
                  mstats->DAY_TRIP,mstats->DAY_FARE,mstats->DAY_FARE_DEC,mstats->DAY_PAID_KM,mstats->DAY_PAID_KM_DEC,mstats->DAY_FREE_KM,mstats->DAY_FREE_KM_DEC,mstats->DAY_WAITING_HR,mstats->DAY_WAITING_MIN,mstats->DAY_POWER_FAIL);				  */
				
		break;//ButtonEvt
	}
				   
				  
				  
				  drv_sim900_sendframe(Gsm.TxBuff,get_size(Gsm.TxBuff));
}


void GsmRun(void)
{
	
	switch (Gsm.TimeStatus)
	{
		case TimerInit:
		switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
					Gsm.TimeStatus=TimerStart;
					break;
					case OkGsm:
					Gsm.TimeStatus=TimerStart;	
					break;
					case GsmConnected:
							Gsm.State			=	Con_TcpConnect;
						    Gsm.NextState		=	Con_TcpConnect;
						    Gsm.OldState		=   Con_TcpConnect;
							Gsm.Tcp_Stage		=	TcpInit;
							Gsm.Tcp_NextState	=	T_Init;
							Gsm.Tcp_OldState	=	T_Init;
							Gsm.Tcp_State		=	T_Init;
							Gsm.MsgStatus		=   MsgInit; 
							Gsm.BuffCnt  		=	0;
							Gsm.MaxDelay		=	60;
							Gsm.Delay			=	2;
							Gsm.Event			=	EvtTcpConnect;	
				 			GsmRing();
				 			Gsm.TimeStatus		=	TimerStart;
					
					break;//GsmConnected,
					case GsmDisconnected:
					nop();
					break;
					case GsmReconnecting:
					nop();
					break;
					case TcpConnecting:
					nop();
					break;
					case TcpConnected:
					Gsm_Control(Tcp_Connection,T_Sending,T_Send,T_Sending,2,20,TimerStart);		
					break;
					case TcpDisconnected:
					nop();
					break;
					case TcpReconnecting:
					nop();
					break;

			    	default:
					break;
				}
	break;//TimerInit
	
		case TimerOver:
			GsmCheckMsg();
				switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
						drv_sim900_send_cmd(4,"AT\r\n");//test
						GsmInitConfig(Con_Running,Con_AT,Con_AT,MsgSend,1,TimerStart); //previous Con_Started
						Gsm.ConnectionStatus=OkGsm;
						GsmDisplayUpdate("Init Gsm",2);
					break;
					case OkGsm:
						GsmInit();
					break;
					case GsmConnected:
						 GsmStayConnected();	
					break;//GsmConnected,
					case GsmDisconnected:
					nop();
					break;
					case GsmReconnecting:
					nop();
					break;
					case TcpConnecting:
						 GsmStayConnected();
					break;
					case TcpConnected:
					

						 Tcp();
						 GsmStayConnected();
					break;
					case TcpDisconnected:
					nop();
					break;
					
					case TcpReconnecting:
					nop();
					break;

			    	default:
					nop();
					break;
				}
	break ;//Timerover
	
	case TimerStop:
			switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
					Init_Sim900();
					Gsm.ConnectionStatus=InitGsm;
					Gsm.State	=	Con_InitState;
					break;
					case OkGsm:
						Init_Sim900();
						Gsm.ConnectionStatus=InitGsm;
						Gsm.State	=	Con_InitState;
					break;
					case GsmConnected:
					nop();
					break;//GsmConnected
					case GsmDisconnected:
					nop();
					break;
					case GsmReconnecting:
					nop();
					break;
					case TcpConnecting:
											drv_sim900_send_cmd(12,"AT+CIPSHUT\r\n");	
											Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);	
											Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);	
					break;
					case TcpConnected:
							drv_sim900_send_cmd(12,"AT+CIPSHUT\r\n");	
							Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);	
							Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);	
					
					break;
					case TcpDisconnected:
					nop();
					break;
					case TcpReconnecting:
					nop();
					break;

			    	default:
					nop();
					break;
				}
							
	break;//TimerStop
	case TimerStart:
	nop();
	break;//TimerStart
	
	
	}
}
void GsmStayConnected()
{
					switch (Gsm.Event)
					{
						case EvtGsmRing:
							GsmDisplayUpdate("Incoming Call",2);
							Gsm_Callabort();
							Gsm.Event				=	EvtTcpConnect;
							Gsm.Delay				=	5;
				 			Gsm.TimeStatus			=	TimerStart;								
						break;
						case EvtGsmMsg:
							GsmDisplayUpdate("Sms Received",2);
							Gsm.Event			    =	EvtTcpConnect;
							Gsm.Delay				=	5;
							Gsm.TimeStatus			=	TimerStart;
						break;
						
						case EvtTcpConnect: //starting hear
							 switch(Gsm.Tcp_Stage)
							 {
								 case TcpInit:
								 GsmDisplayUpdate("  Running    ",2);								 
								 Gsm_Control(TcpCsq,T_Init,T_Started,T_Init,2,60,TimerStart);
								 break;//TcpInit
								 
								 case TcpCsq:
								 CheckCsq();
								 break;//TvpCsq

								 case Tcp_Connection:
								 Gsm.ConnectionStatus=TcpConnecting;
								 Tcp_Init();
								 break;//Tcp_Connection
								 
								 case Tcp_Connected:
								 Gsm_Control(Tcp_Connection,T_Sending,T_Send,T_Sending,2,20,TimerInit);

								 Gsm.ConnectionStatus=TcpConnected; 
								 break;//			
							 }
						break;
								
						case EvtTcpConnected:
							Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);
						break;//EvtTcpConnected		
												
						case EvtGsmInit:
							Gsm.Event			    =	EvtTcpConnect;
						break;
						
						default:
							Gsm.Event=Gsm.Event;
						break;
					}
			
}

void GsmInitConfig( enum GsmCon_state _State,
				    enum GsmCon_state _NextState,
 					enum GsmCon_state _OldState,
					enum GsmMsgEvt 	  _MsgStatus,
					unsigned int 	  _Delay, 
					enum TimeEvent 	  _TimeStatus){
					
					Gsm.State		=_State;	
					Gsm.NextState	=_NextState;
					Gsm.OldState	=_OldState;
					Gsm.MsgStatus	=_MsgStatus;
					Gsm.Delay		=_Delay;
					Gsm.TimeStatus	=_TimeStatus;
						
}
	 
	 

void CheckCsq()
{

	switch (Gsm.Tcp_State)
	{
		case T_Init:
			#ifdef DebugOn
				   GsmDisplayUpdate("Csq        ",1)	;	
			#endif	
			GsmClearBufffer();
			drv_sim900_send_cmd(6,"AT+CSQ\r\n");
			Gsm_Control(TcpCsq,T_Started,T_Started,T_Init,2,60,TimerStart);
		break;
		case T_Started:
		Gsm.Tcp_State		=T_Started;
		break;
		case T_CsqReceived:
		GsmClearBufffer();
		if(Gsm.Rssi<=2)
		{
		Gsm.Tcp_State=T_CsqLow;	
		}
		else if(Gsm.Rssi<99)
		{
			Gsm.Tcp_State=T_CsqHigh;	
		}
		else if(Gsm.Rssi==99)
		{
			Gsm.Tcp_State=T_CsqNoSignal;
		}
		
		
		break; //CsqReceived
		
		case T_CsqHigh:
		Gsm.Tcp_State=T_completed;
		break; //Csqhigh
		case T_CsqLow:
		Gsm.Tcp_State=T_completed;
		break; //CsqLow
		case T_CsqNoSignal:
		Gsm.ConnectionStatus=GsmDisconnected;
		GsmDisplayUpdate("NoSignal",1);
		Gsm.Tcp_State=T_completed;
		break; //CsqNoSignal
		
		case T_completed:
		GsmDisplayUpdate(Gsm._Csq,1);
		Gsm_Control(Tcp_Connection,T_Init,T_Started,T_Init,2,20,TimerStart);
		break;//T_completed
		
	}
	
	
}	 
void GsmInit()
{


		switch (Gsm.State)
				{
				case Con_AT:
					#ifdef DebugOn
	  			    GsmDisplayUpdate("Ateo    ",1)	;	
					#endif
				    drv_sim900_send_cmd(6,"ATE0\r\n");
					GsmInitConfig(Con_Running,Con_ATOK,Con_AT,MsgSend,1,TimerStart);
				break;
				case Con_ATOK:
					GsmDisplayUpdate("Cnmi    ",1)	;
					drv_sim900_send_cmd(13,"AT+CNMI=2,1\r\n");
					GsmInitConfig(Con_Running,Con_CNMI,Con_ATOK,MsgSend,1,TimerStart);				
				break;
				case Con_CNMI:
				  drv_sim900_send_cmd(22,"AT+CSMP=17,167,0,241\r\n"); 
				  GsmInitConfig(Con_Running,Con_CSMP,Con_CNMI,MsgSend,1,TimerStart);
				break;

				case Con_CSMP:
  					    drv_sim900_send_cmd(11,"AT+CMGF=1\r\n");
						GsmInitConfig(Con_Running,Con_CMGF,Con_CSMP,MsgSend,1,TimerStart);				
				break;  
				case Con_CMGF:
					    drv_sim900_send_cmd(20,"AT+CMGDA=\"DEL ALL\"\r\n"); 
						GsmInitConfig(Con_Running,Con_CIPSHUT,Con_CMGF,MsgSend,1,TimerStart);								
				break;	
 				case Con_CIPSHUT:
								
	                    drv_sim900_send_cmd(12,"AT+CIPSHUT\r\n");
						GsmInitConfig(Con_Running,Con_Exit,Con_CIPSHUT,MsgSend,1,TimerStart);														
				break;	
				case Con_Exit:
						Gsm.ConnectionStatus	=	GsmConnected;
						#ifdef DebugOn
								   GsmDisplayUpdate("Connected",1)	;	
						#endif	
							Gsm.TimeStatus		    =	TimerInit;
				break;				
				default:
							Gsm.State=Gsm.State;
				break;
				
				case Con_Running:
						switch(Gsm.MsgStatus)
						{
								case MsgOk:
								Gsm.State=Gsm.NextState;
								GsmClearBufffer();
								break;//Msgok
						}
						if(Gsm.TimeStatus==TimerStop)
						{
						Gsm.State=Con_Started;	
						}
			
				
				break;//Con_Running					   
		 }/***Gsm State end***/
		
}



void sim900_call()
{


	drv_sim900_send_cmd(5,"ATD+91");
	drv_sim900_send_cmd(get_size(Gsm.MobNo),Gsm.MobNo);
	drv_sim900_send_cmd(3,";\r\n");
	//drv_sim300_send_cmd(get_size("ATD+919824190847;\r\n"),"ATD+919824190847;\r\n");
}



void Gsm_State()
{
		GsmInitConfig(Con_InitState,Con_InitState,Con_InitState,MsgInit,0,TimerInit);
		Gsm.Tcp_Stage			=	TcpInit;
		Gsm.Tcp_NextState		=	T_Init;
		Gsm.Tcp_OldState		=	T_Init;
		Gsm.Tcp_State			=	T_Init;	
		Gsm.TickCnt				=	0;
		Gsm.BuffCnt  			=	0;
		Gsm.MsgLenght			=   0;
		Gsm.Display				=	Done; //No change
		Gsm.ConnectionStatus	=	InitGsm;
		strcpy(Gsm.Ip_ADD,"103.241.144.173");
	    strcpy(Gsm.PortNo,"31000"); 
	/*	strcpy(Gsm.Ip_ADD,"www.google.com");
	    strcpy(Gsm.PortNo,"8080"); */
	//	strcpy(Gsm.Ip_ADD,"54.251.99.26");
	//	strcpy(Gsm.PortNo,"9501");
		strcpy(Gsm.D_Id  ,"60");
						
}
void GsmDisplayUpdate(char * msg,char loc)
{
	switch (loc)
	{
		case 1:
					strcpy(Gsm.Gsm_Status,msg);
		break;
		
		case 2:
					strcpy(Gsm.Gsm_Sms,msg);
		break;
	}

			Gsm.Display				=	Update;	
}

void Init_Sim900(void)
{

			if(Gsm.State	==	Con_InitState)
				{
					Gsm.MaxDelay		=	30;
					ReStart();
				}
			else if(Gsm.State 	==	Con_Started)
				{
					GsmDisplayUpdate("Restart ",1);	
					ReStart();
					Gsm.MaxDelay		=	45;
				}
			GsmInitConfig(Con_Started,Con_Started,Con_Started,MsgInit,8,TimerInit); //timerinit	
			Gsm.BuffCnt  			=	0;   //rxbuff start location is 0
			Gsm_Tick();
			GsmEnableComm();
			GsmStartReceive();
	       	drv_sim900_send_cmd(4,"AT\r\n");//test	
}



void GsmRing()
{
	 R_INTC_CreateExtInterrupt(PDL_INTC_NMI,PDL_INTC_RISING|PDL_INTC_LVD_ENABLE,GsmRing,1);
     GsmCheckMsg();
}


void Gsm_Control(enum _TcpStage _TStage,
				 enum _TcpState _TState,
				 enum _TcpState _TNextState,
				 enum _TcpState _TOldState,
				 unsigned int _TMin,
				 unsigned int _TMax,
				 enum TimeEvent _TEvt)
									{
			Gsm.Tcp_Stage		=_TStage;
			Gsm.Tcp_State		=_TState;
			Gsm.Tcp_NextState	=_TNextState;
			Gsm.Tcp_OldState	=_TOldState;
			Gsm.Delay			=_TMin;
			Gsm.MaxDelay		=_TMax;
			Gsm.TimeStatus		=_TEvt;
}


void GsmClearBufffer()
{
	unsigned int i=0;
	i=GsmRXBufferSize;
	while(--i!=0)
	{
	GsmPtr->Rxbuff[i]=0;	
	}	
	Gsm.BuffCnt=0;	
}
void OnModemReceive(void)
{

				 Gsm.MsgStatus=MsgStarted;
	      		 Gsm.Rxbuff[++Gsm.BuffCnt]=Gsm.RxTemp;

      			R_SCI_Receive(GSMCommNo,PDL_NO_DATA,&Gsm.RxTemp,1,OnModemReceive,OnGsmError);
	  			SCI6.SCR.BYTE |= 0x30;
				
}
void OnGsmError(void)
{
	SCI6.SSR.BYTE = (uint8_t)(BIT_7 | BIT_6);
	SCI6.SSR.BYTE &= ~(BIT_5);
    R_SCI_Receive(GSMCommNo,PDL_NO_DATA,&Gsm.RxTemp,1,OnModemReceive,OnGsmError); 
}
void ReStart()
{

 	PowerKey		=	ON;
	__delay_cycles(290000);
	__delay_cycles(990000);    
    __delay_cycles(990000);
    __delay_cycles(990000);
    __delay_cycles(990000);
	__delay_cycles(290000);
	__delay_cycles(990000);    
    __delay_cycles(990000);
    __delay_cycles(990000);
    __delay_cycles(990000);						
	PowerKey		=	Off;
	__delay_cycles(290000);
	__delay_cycles(990000);    
    __delay_cycles(990000);
    __delay_cycles(990000);
    __delay_cycles(990000);

}
void GsmEnableComm()
{
	R_SCI_Create(GSMCommNo,PDL_SCI_ASYNC|PDL_SCI_TX_CONNECTED |PDL_SCI_RX_CONNECTED | PDL_SCI_CLK_INT_IO| PDL_SCI_8N1| PDL_SCI_STOP_1 ,19200,1); 
    SCI6.SCR.BYTE |= 0x30;
}

void GsmDisableComm()
{
R_SCI_Destroy(GSMCommNo)	;
}

void drv_sim900_sendframe(uchar * buf,unsigned int len) 
{
  drv_sim900_send_cmd(get_size(CIPSEND),CIPSEND);   // send command
 // mdelay(129530);//mdelay(149530);
  __delay_cycles(9999999);
  
  drv_sim900_send_cmd(len,buf);                   // user data
 // mdelay(140);
  __delay_cycles(1400);
  drv_sim900_send_cmd(1,EOD);                     // end of data
  
}

void GsmStartReceive()
{
	R_SCI_Receive(GSMCommNo,PDL_NO_DATA,&Gsm.RxTemp,1,OnModemReceive,OnGsmError); 
}
void drv_sim900_send_cmd(int size, unsigned char const * str)
{
	unsigned char i;
	  i = 0;
	  while(str[i])
	  {
		while(SCI6.SSR.BIT.TDRE == 0);
		
		SCI6.TDR = str[i]; 
		SCI6.SSR.BIT.TDRE =1;
		i++;
	  }
	  SCI6.SCR.BIT.TE = 0;
}
void Gsm_Callabort(void)
{
    drv_sim900_send_cmd(5,"ATH\r\n");  //disconnect connection 
}
void sim900_accept()
{
	drv_sim900_send_cmd(5,"ATA\r\n");  //answer connection 
}