/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :August 23, 2013                                         */
/*  Project name        :SmartNav                                                      */
/*  FileName              :*/
/*  CPU GROUP        :25                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/



#ifndef   __CreateObj_h_
#define  __CreateObj_h_


typedef unsigned int Uint16;
typedef struct Button Button;
typedef struct Button* ButtonPointer;



#define U_16 	Uint16

#define Form1Id			1
#define BtHiredId		2
#define BtTopayId		3
#define BtVacentId		4
#define BtStatusId		5
#define BtAcceptId		6
#define BtEngageId		7
#define BtEngagedId		8

#define TBLatId	 	9
#define TBLonId	 	10
#define TBSpdId	 	11
#define TBGsmId	 	12
#define TBSmsId	 	13
#define TBRtcId		14

#define LastId 			BtEngagedId //  Put The Last Id


 


void CreatFormObj(void * Frm,unsigned int x,unsigned int y,unsigned int wt,unsigned int ht,unsigned int id,unsigned char type);




unsigned char LcdButton(Button *);
//unsigned char BT_Pressed(unsigned int *x1,unsigned int *x2 ,unsigned int *y1,unsigned int *y2 );

extern  struct TButton  	TB_Hired,TB_Topay,TB_VACANT,TB_Status,TB_Accept,TB_Engage,TB_Engaged;
extern 	struct TForm		Tfrm,Tfrm1;
extern  struct xEvent		e,eFrm1,eBt1,eBt2,eBt3,eBt4,eBt5,eBt6,eBt7,eBt8;
extern  struct TCheckbox	Tcb1,Tcb2;
extern	struct TTextbox 	TtbLat,TtbLon,TtbSpeed,TtbGsm,TtbSms,TtbRtc;
extern 	struct TSpinbox 	Tsb1,Tsb2;
extern 	struct TCombobox	TCm1,TCm2;
extern  struct TListbox 	TLb1,TLb2;
extern 	struct TKeypad 		TKp1,TKp2;

#endif