/**********************************************************************************/
/*                                                                                */
/*                                                                                */
/*  DATE                   :September 05, 2013                                    */
/*  Project name           :SmartNav                                              */
/*  FileName               :													  */
/*  CPU GROUP              :25                                                        */
/*  Designer Engg          :Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/



#ifndef   	__MainForm_h_
#define  	__MainForm_h_

#include "xWidget.h"
#include "xEvent.h"





void CreateForm_Start(void);
void DisplayForm_Start(void);

#endif