


/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :March 07, 2014,TIME->14:48:28                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :xEvent.h*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#ifndef  __xEvent_h_

#define __xEvent_h_



#include "xWidget.h"
#include "CreateObj.h"
#define MSG_LCLICK    0x01
#define FLAG_MDOWN    0x01

#define SOURCE_MOUSE    0x01
#define SOURCE_KEYPAD   0x02


void TButtonCallback(void * obj);
void TSpinboxCallback(void * obj);
void xEventDispatch(struct xEvent * e);
void TTextboxCallback(void * obj,struct xEvent * e);
void TComboboxCallback(void * obj,struct xEvent * e);
void TKeypadCallback(void * obj,struct xEvent * e);
void TSpinboxCallback(void * obj,struct xEvent * e);
void TCallbackCheckbox(void * obj,struct xEvent * e);
void TCallbackListbox(void * obj,struct xEvent * e);

#endif