/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :March 07, 2014,TIME->14:48:49                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :xWidget.h*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#ifndef  __xWidget_h_

#define __xWidget_h_




#define LCD_X_RES                  320
#define LCD_Y_RES                  240
#define LCD_CACHE_SIZE             9600

#define    PIXEL_OFF   0   
#define    PIXEL_ON    1
#define    PIXEL_XOR   2



#define TYPE_FORM     1
#define TYPE_BUTTON   2
#define TYPE_TEXTBOX  3
#define TYPE_SPINBOX  4
#define TYPE_COMBOBOX 5
#define TYPE_LISTBOX  6
#define TYPE_CHECKBOX 7 
#define TYPE_KEYPAD   8




//define Event message
#define SPIN_UP    1
#define SPIN_DOWN  2
// xWidget Font Library
extern const unsigned char  f8x8a[256][8];        // 8x8 
extern unsigned char const  font_12x18[];
extern unsigned int x,y,w,h,offsetx,offsety;      // temp varialble 
extern void * active_form;
extern struct TControl * o;
extern struct TButton *  mBt;
extern struct TTextbox * mTx;
extern struct TSpinbox * mSb;

struct xEvent
{
     unsigned char  source;
     unsigned char  message;
     unsigned char  flag;
     unsigned int x,y;
};

struct TControl
{
    unsigned int id;
    unsigned int x;
    unsigned int y;
    unsigned int width;
    unsigned int height;
    unsigned char type;
    struct TForm * parent;
    struct TControl * next;
    void (*callback)(struct xEvent *,void * obj);
};

struct TForm
{
     struct TControl p;
     char *caption;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
};
struct TButton
{
     struct TControl p;

     char *caption;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
    
};
struct TCheckbox
{
     struct TControl p;
     char *caption;
     char state;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
    
};

struct TTextbox
{
     struct TControl p;
     char *text;
     unsigned char max;
     unsigned int offset;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
};

struct TSpinbox
{
     struct TControl p;
     int value;
     int max,min;
     unsigned char ndigit;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
};

struct TCombobox
{
     struct TControl p;
     int index;
     unsigned char count;
     char  *list;
     char state;
     unsigned char ndigit;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
};
struct TListbox
{
     struct TControl p;
     int index;
     unsigned char count;
     char  *list;
     char state;
     unsigned char ndigit;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
};
struct TKeypad
{
     struct TControl p;
     char state;
     struct TTextbox *tx;
     unsigned int forecolor;
     unsigned int backcolor;
     unsigned char  font;
};


extern void TCreateForm(unsigned int id ,void * obj,char * caption,void * next);
extern void TCreateButton(void * parent ,void * obj,char * cap,void * next);
extern void TCreateTextbox(void * parent ,void * obj,char * text,void * next);
extern void TCreateSpinbox(void * parent ,void * obj,int value,void * next);
extern void TCreateCombobox(void * parent ,void * obj,char  *list,void * next);
extern void TCreateListbox(void * parent ,void * obj,char * list,void * next);
extern void TCreateCheckbox(void * parent ,void * obj,char * cap,void * next);
extern void TCreateKeypad(void * parent ,void * obj,void * next);

extern void TRedrawKeypad(void * obj);
extern void TRedrawButton(void * obj);
extern void TRedrawTextbox(void * obj);
extern void TRedrawSpinbox(void * obj);
extern void TRedrawCombobox(void * obj);
extern void TRedrawForm(void * obj);
extern void TRedrawListbox(void * obj);
extern void TRedrawCheckbox(void * obj);
extern void LoadForm1();
extern void xEventDispatch(struct xEvent * e);



void TCursorUpdate(void * obj);


#endif