/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :May 05, 2014,TIME->14:02:02                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :BSP.c*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#include "BSP.h"






void update_rtc()
{
	Start_RTC();
	PtrPCF8563->SEC	=	0; // SEC
	PtrPCF8563->MIN	= 	50; // MINUTE
	PtrPCF8563->HOUR=   2; // HOUR
	
    PtrPCF8563->DAYS=20; // week day
	
	PtrPCF8563->WEEKDAYS=1; // DAYS
	PtrPCF8563->MONTH=5; // month
    PtrPCF8563->YEAR=14; //year
        
    Write_RTC();
}

unsigned short get_size(const unsigned char * buf)
{
   int i=0;
   while(buf[i])
   {
      i++;
      if(i>220)
      {
         return 0; 
      }
       
   }
   return i;
}



void display_company()
{
    unsigned short i;
	i  = get_size((char * )0x00107802);
	if(i>0 && i<30)
	LcdPutMsg2((char * )0x00107802,(240-(i*8))>>1,45);	   
}
void tick_flag()
{
		uint8_t Irq5_Status;
		
		++GpsPtr->SecTick;
	
		R_TMR_CreateOneShot(PDL_TMR_UNIT0,PDL_TMR_OUTPUT_OFF,1,tick_flag,4); 
		if(GpsPtr->SecTick==5)
		{
		enable_gps();	
		}
	
}

void Gsm_Tick()
{
	uint8_t err=0;	


		err=R_TMR_CreateOneShot(PDL_TMR_UNIT1,PDL_TMR_OUTPUT_OFF|PDL_TMR_CPU_ON,0.10,Gsm_Tick,3); 
	/*	if(!err)
		{
			R_TMR_Destroy(PDL_TMR_UNIT1);
			err=R_TMR_CreateOneShot(PDL_TMR_UNIT1,PDL_TMR_OUTPUT_OFF|PDL_TMR_CPU_ON,GsmPtr->Delay,Gsm_Tick,3); 
		}*/
		++GsmPtr->L_Tick;
					switch(GsmPtr->TimeStatus)
					{
						case TimerStart:
						GsmPtr->TickCnt 	=              0;
						GsmPtr->TimeStatus  =	TimerRunning;
						break; //TimerStart
					
						case TimerOver:
							++GsmPtr->TickCnt;
						if(GsmPtr->TickCnt>GsmPtr->MaxDelay)
						{
						GsmPtr->TimeStatus  =	TimerStop;	
						}
						else
						{
						;
						}
						break; //TimerOver
					
						case TimerRunning:
							++GsmPtr->TickCnt;
							if(GsmPtr->TickCnt>=(unsigned int)(GsmPtr->Delay))
						    {
						 	GsmPtr->TimeStatus =TimerOver;
							}
					    break;  //TimerRunning

					}
					#ifdef DebugOn
		 sprintf(&GsmPtr->Tick,"%d,d=%d,M=%d ",GsmPtr->TickCnt,GsmPtr->Delay,GsmPtr->MaxDelay);
		 GsmPtr->Display				=	Update;	
		#endif
	
		
}

void Pen_flag()
{

	    R_INTC_ControlExtInterrupt(	PDL_INTC_IRQ5,PDL_INTC_DISABLE | PDL_INTC_CLEAR_IR_FLAG);
		 R_INTC_CreateExtInterrupt(PDL_INTC_IRQ5,PDL_INTC_LOW ,Pen_flag,1); 		
	    MainDispaly();
}

void buzzer_sound()
{
	unsigned int i;
	for(i=0;i<450;i++)        // repeat for 100ms
	{
	  Buzzer = ~Buzzer;			// Toggle Buzzer
      __delay_cycles(1150);		    // 120us  delay
	}
}
void tone(char n)
{
	 while(n--)
	 {
		 buzzer_sound();
		 __delay_cycles(2500);
	 }
}

void __delay_cycles(unsigned long ms)
{ 
	 while(ms--){};
} 


void Init_SmartNavi()
{

	HardwareSetup();
	R_TMR_CreateOneShot(PDL_TMR_UNIT0,PDL_TMR_OUTPUT_OFF,1,tick_flag,4);
    R_INTC_CreateExtInterrupt(PDL_INTC_IRQ5,PDL_INTC_LOW ,Pen_flag,1); 		
		
	
	//	sendtoRTC();
	    Init_ADS7843();
		#ifdef GpsOn
	    getPos();
		#endif
		tone(1);
    	font_index();
    	font_index1();
    	LcdInit();
		LcdClear();
	    Gsm_State();		//initialize variable
		Init_Sim900();

}