/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :May 05, 2014,TIME->14:01:41                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :BSP.h*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#ifndef  __BSP_h_

#define  __BSP_h_


#include "ads7843.h"
#include "hwsetup.h"
#include "Gps.h"
#include "Sim900.h"
#include "i2c.h"
#include "Display/xEvent.h"
#include "Display/xWidget.h"
#include "SmartNav.h"






#include "iodefine_rpdl.h"
#include "r_pdl_cmt.h"
#include "r_pdl_intc.h"
/* IO port RPDL function definitions */
#include "r_pdl_io_port.h"
#include "r_pdl_sci.h"
#include "r_pdl_tmr.h"
#include "r_pdl_wdt.h"
#include "r_pdl_lvd.h"
#include "r_pdl_intc.h"
/* General RPDL function definitions */
#include "r_pdl_definitions.h"

typedef unsigned char uchar;


/********************************************************************************************/
/*  DATE			:May 05, 2014,TIME->14:07:54             */
/*  FileName		:SmartNav.h 			*/
/*  Designer Engg	:Nithin.P                          	                */
/* 	DECLARATION */
/*                                                                                         */
/*                                                                                         */
/******************************************************************************************/


enum TickEvent{
TickEvt_Off=0,
TickEvt_On,
TickEvt_Update,
};

//typedef struct xEvent* EventPointer;



extern void update_rtc();
extern void __delay_cycles(unsigned long ms);
extern void buzzer_sound();
extern void tone(char n);
extern void Gsm_Tick();
#endif
