/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :May 08, 2014,TIME->14:39:05                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :Gps.c*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#include "Gps.h"


static struct GpsEvent Gps;


GpsEventPointer GpsPtr=&Gps;
romchar GPRMC[]={"GPRMC" };



volatile char RX5BUF;


void enable_gps()
{
	R_SCI_Create(5,PDL_SCI_ASYNC|PDL_SCI_RX_CONNECTED | PDL_SCI_8N1| PDL_SCI_STOP_1 , 9600,8); 
	R_SCI_Receive(5,PDL_NO_DATA,&RX5BUF,1,OnGpsReceive,OnGpsError); 
	SCI5.SCR.BIT.RIE = 1;

}


void OnGpsReceive(void)
{
	static unsigned int i;
  	char * ans 	= NULL;
	char * valid= NULL;
	char * End	=NULL;
	char * Lat =NULL;
	char * Lon =NULL;
	char * Time=NULL;


	/*
	Need to consider the if null char is required
		Lat=strstr(Gps.Lat,",N");
		Lon=strstr(Gps.Lon,",E");
		*(Lat+1)=0;			
		*(Lon+1)=0;
		||
		*/
 	Gps.GpsBuf[Gps.BuffCnt++]=RX5BUF;
		Gps.State=RECEIVED;
	if(Gps.BuffCnt>200)
	{
		
		ans=strstr(Gps.GpsBuf,GPRMC);
		if(ans!=NULL)
		{
			

		i=strlen(ans);
	/*	if((*(ans+16)=='A')&&(i>30))
		{
		i=strlen(ans);
		}*/
		if((i<30)||(*(ans+17)!='A'))
		{
		Gps.State=INVALID;			
		Gps.BuffCnt=0;
		}
		else 
		{
		Gps.BuffCnt=0;			
		Time=strstr(ans,"C,");
		Lat=strstr(ans,"A,");
		Lon=strstr(ans,"N,");
			if((Time!=NULL)&&(Lat !=NULL)&&(Lon !=NULL))
			{
			strncpy(Gps.Time,Time+2,6);
			strncpy(Gps.Lat,Lat+2,11);
			strncpy(Gps.Lon,Lon+2,12);
			Gps.State=UPDATED;
			}
		}
		}
		else
		{
		Gps.BuffCnt=0;
		}
	
	}

  R_SCI_Receive(5,PDL_NO_DATA,&RX5BUF,1,OnGpsReceive,OnGpsError); 

}


void OnGpsError(void)
{
	SCI5.SSR.BYTE = (uint8_t)(BIT_7 | BIT_6);
	SCI5.SSR.BYTE &= ~(BIT_5);
	GpsPtr->SecTick=0;
   	R_SCI_Create(5,PDL_SCI_ASYNC|PDL_SCI_RX_DISCONNECTED | PDL_SCI_8N1| PDL_SCI_STOP_1 , 9600,1); 
}

void GpsInit()
{
		strcpy(Gps.Lat,"0000.0000,N");
		strcpy(Gps.Lon,"00000.0000,E");
		strcpy(Gps.Speed,"0.0");
		strcpy(Gps.Time,"120000");
		Gps.State=INITIAL;
		Gps.SecTick=0;
		Gps.BuffCnt=0;
}


void gps_process()
{
	switch(Gps.State)	
	{
		case INITIAL:
		enable_gps();
		break;
		
		case STARTED:
		GpsPtr->SecTick=0;
        R_SCI_Create(5,PDL_SCI_ASYNC|PDL_SCI_RX_DISCONNECTED | PDL_SCI_8N1| PDL_SCI_STOP_1 , 9600,1); 
		break;//UPDATED
		
		case RECEIVED:
		
		break;//RECEIVED
	}
	 		   

}