/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :May 08, 2014,TIME->14:39:14                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :Gps.h*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#ifndef  __Gps_h_
#define __Gps_h_

#include "bsp/Bsp.h"

enum GpsState{
INITIAL,
RECEIVED,
INVALID,
UPDATED,
STARTED,
};


struct GpsEvent{
	unsigned char Lat[14];
	unsigned char Lon[14];
	unsigned char Speed[5];
	unsigned char Time[7];
	enum GpsState State;
	unsigned char SecTick;
	unsigned char BuffCnt;

	char GpsBuf[225];

};

typedef struct GpsEvent * GpsEventPointer;


extern GpsEventPointer GpsPtr;

void OnGpsReceive(void);
void OnGpsError(void);
void enable_gps();
void gps_process();
void GpsInit();

#endif